### ISSUE TITLE
Add configurable sleep between database operations.

### ISSUE THREAD

**Issue by jemc** [tarolandia/cassandra-schema#7]
There is a Cassandra bug, where schema changes executed in quick succession can result in internal corruption:

https://stackoverflow.com/questions/29030661/creating-new-table-with-cqlsh-on-existing-keyspace-column-family-id-mismatch#answer
https://issues.apache.org/jira/browse/CASSANDRA-5025

In such cases, the only option is to do a rolling restart of the cassandra cluster, which is a major inconvenience for deploying schema updates.

We have a schema update where this bug happens fairly reliably, and are looking for a workaround.

Sleeping in between schema update commands seems like viable workaround, unfortunate as it may be. It would be nice if `cassandra-schema` could provide such an option.

**Comment by tarolandia** [comment]
@jemc I can add a new option `query_delay` (with a default value `0`) that will allow you specify the time to sleep after each command, in milliseconds.

**Comment by jemc** [comment]
That sounds good - thanks.

**Comment by tarolandia** [comment]
Closed by #8
